#!/usr/bin/env python3
"""
Add example sentences to all words in words.csv
"""

import csv

# Example sentences for each word (appropriate for 12-year-old learners)
EXAMPLE_SENTENCES = {
    # Numbers and ordinals
    '-th': 'Today is my 12th birthday.',
    'fifth': 'She finished in fifth place in the race.',
    'sixth': 'This is the sixth book in the series.',

    # Quantity expressions
    'a couple of': 'I need a couple of minutes to finish.',
    'a good deal': 'He knows a good deal about computers.',
    'a great deal': 'She talks a great deal.',
    'a little': 'Add a little sugar to the tea.',
    'a number of': 'A number of students were absent today.',
    'a bit': 'I\'m a bit tired after the game.',
    'all sorts of': 'The shop sells all sorts of toys.',
    'most': 'Most students like sports.',
    'too much': 'Don\'t eat too much candy.',
    'very much': 'I like this game very much.',
    'quite a lot': 'He reads quite a lot of books.',
    'plenty of': 'There is plenty of food for everyone.',
    'few': 'Few people came to the party.',
    'several': 'I have several friends in my class.',
    'each': 'Each student has their own desk.',
    'none': 'None of the students knew the answer.',
    'couple': 'The couple went for a walk.',

    # Abilities and characteristics
    'ability': 'She has the ability to speak three languages.',
    'able': 'I was able to finish my homework on time.',
    'active': 'My grandfather is very active for his age.',
    'activity': 'Swimming is my favorite activity.',
    'intelligent': 'She is a very intelligent girl.',
    'clever': 'That was a clever solution to the problem.',
    'smart': 'He is smart and studies hard.',
    'brilliant': 'She had a brilliant idea.',
    'stupid': 'Don\'t say stupid things.',
    'silly': 'Stop being silly and do your work.',
    'crazy': 'That\'s a crazy idea!',
    'mad': 'Are you mad at me?',
    'wise': 'My grandmother gave me wise advice.',

    # Position and location
    'about': 'The book is about animals.',
    'above': 'The bird flew above the trees.',
    'abroad': 'My uncle lives abroad in Canada.',
    'across': 'We walked across the bridge.',
    'against': 'He leaned against the wall.',
    'along': 'We walked along the beach.',
    'along with': 'She came along with her sister.',
    'among': 'He sat among his friends.',
    'around': 'The children ran around the playground.',
    'at': 'I\'ll meet you at the school.',
    'away': 'He lives far away from here.',
    'back': 'Come back soon!',
    'below': 'The fish swam below the surface.',
    'beside': 'Sit beside me.',
    'between': 'The ball is between the two trees.',
    'beyond': 'The mountains are beyond the river.',
    'forward': 'Take one step forward.',
    'ahead of': 'She walked ahead of me.',
    'behind': 'The cat is hiding behind the sofa.',
    'near': 'The school is near my house.',
    'nearby': 'There is a park nearby.',
    'opposite': 'The store is opposite the bank.',
    'through': 'We drove through the tunnel.',
    'middle / in the middle': 'Put the vase in the middle of the table.',
    'toward': 'He walked toward the door.',
    'towards': 'She ran towards her mother.',

    # Time expressions
    'after': 'Let\'s play after school.',
    'after all': 'He decided to come after all.',
    'afternoon': 'I have piano lessons in the afternoon.',
    'ago': 'I saw that movie two weeks ago.',
    'already': 'I already finished my homework.',
    'all the time': 'She talks all the time.',
    'always': 'I always brush my teeth before bed.',
    'at first': 'At first, I didn\'t like the book.',
    'at last': 'At last, we arrived home.',
    'at once': 'Do your homework at once!',
    'at present': 'At present, I am studying English.',
    'at the same time': 'They arrived at the same time.',
    'before': 'Wash your hands before dinner.',
    'by chance': 'I met her by chance at the mall.',
    'by the time': 'By the time I arrived, the movie had started.',
    'by the way': 'By the way, did you call your mom?',
    'during': 'I fell asleep during the movie.',
    'early': 'I wake up early every morning.',
    'ever': 'Have you ever been to London?',
    'ever since': 'Ever since that day, we\'ve been friends.',
    'finally': 'Finally, the rain stopped.',
    'first of all': 'First of all, let me introduce myself.',
    'in time': 'We arrived in time for dinner.',
    'late': 'Don\'t be late for school.',
    'lately': 'I haven\'t seen her lately.',
    'long ago': 'Long ago, there were dinosaurs.',
    'long before': 'She left long before I arrived.',
    'moment': 'Wait a moment, please.',
    'never': 'I never eat breakfast.',
    'now': 'Let\'s go now.',
    'once': 'I visited Paris once.',
    'once again': 'Let\'s try once again.',
    'once more': 'Sing the song once more.',
    'often': 'I often play basketball.',
    'on time': 'The train arrived on time.',
    'recently': 'I recently started learning piano.',
    'since': 'I\'ve lived here since 2020.',
    'soon': 'Dinner will be ready soon.',
    'sometimes': 'Sometimes I walk to school.',
    'still': 'Are you still awake?',
    'till': 'Wait here till I come back.',
    'today': 'Today is Monday.',
    'tonight': 'We\'re having pizza tonight.',
    'usually': 'I usually go to bed at 9 PM.',
    'when': 'When will you finish?',
    'while': 'I read a book while waiting.',
    'yet': 'I haven\'t finished yet.',
    'not yet': 'Are you ready? Not yet.',

    # Actions and verbs
    'accept': 'I accept your apology.',
    'act': 'You must act quickly.',
    'to act in a play': 'She loves to act in a play.',
    'add': 'Add two cups of flour to the bowl.',
    'admit': 'I admit I made a mistake.',
    'advertise': 'They advertise on TV.',
    'advise': 'I advise you to study hard.',
    'afford': 'We can\'t afford a new car.',
    'agree': 'I agree with you.',
    'aim': 'Aim for the target.',
    'allow': 'My parents allow me to stay up late on weekends.',
    'announce': 'The teacher will announce the winner.',
    'answer': 'Please answer my question.',
    'apologize': 'You should apologize for being rude.',
    'appear': 'Suddenly, a rabbit appeared.',
    'apply to': 'This rule applies to everyone.',
    'argue': 'Don\'t argue with your sister.',
    'arrange': 'Let\'s arrange the chairs in a circle.',
    'arrive at': 'What time will you arrive at the station?',
    'ask': 'May I ask you a question?',
    'attack': 'The dog might attack if scared.',
    'attend': 'All students must attend the meeting.',
    'avoid': 'Try to avoid making noise.',
    'bake': 'Let\'s bake cookies together.',
    'base': 'The story is based on real events.',
    'based on': 'This movie is based on a true story.',
    'beat': 'Our team beat them 3-1.',
    'become': 'I want to become a doctor.',
    'begin': 'Let\'s begin the lesson.',
    'behave': 'Please behave nicely at dinner.',
    'believe': 'I believe you can do it.',
    'belong to': 'This book belongs to me.',
    'bite': 'My dog doesn\'t bite.',
    'blame': 'Don\'t blame me for this.',
    'blow': 'The wind blows strongly today.',
    'boil': 'Boil the water before drinking.',
    'borrow': 'Can I borrow your pen?',
    'bother': 'Don\'t bother me now, I\'m busy.',
    'don\'t bother': 'Don\'t bother cooking, we\'ll order pizza.',
    'break': 'Be careful not to break the glass.',
    'breathe': 'Take a deep breath and breathe slowly.',
    'bring': 'Please bring your books tomorrow.',
    'build': 'They are building a new school.',
    'burn': 'Don\'t burn the toast.',
    'buy': 'I need to buy some milk.',
    'call': 'I\'ll call you later.',
    'cancel': 'We had to cancel the trip.',
    'care': 'I really care about my friends.',
    'carry': 'Can you carry this bag?',
    'carry out': 'We will carry out the plan tomorrow.',
    'catch': 'Try to catch the ball.',
    'cause': 'What caused the accident?',
    'celebrate': 'Let\'s celebrate your birthday!',
    'change': 'I need to change my clothes.',
    'charge': 'How much do you charge for this?',
    'check': 'Check your answers before submitting.',
    'choose': 'You can choose any color you like.',
    'clean': 'Please clean your room.',
    'climb': 'The children love to climb trees.',
    'close': 'Close the door, please.',
    'collect': 'I collect stamps as a hobby.',
    'come': 'Come here, I want to show you something.',
    'compare': 'Compare these two pictures.',
    'complain': 'She always complains about everything.',
    'complete': 'Did you complete your homework?',
    'connect': 'Connect the dots to make a picture.',
    'consider': 'I\'ll consider your suggestion.',
    'contain': 'This box contains old toys.',
    'continue': 'Let\'s continue reading the story.',
    'control': 'Try to control your anger.',
    'cook': 'My mother cooks delicious meals.',
    'copy': 'Don\'t copy from your friend.',
    'cost': 'How much does this cost?',
    'count': 'Count to ten slowly.',
    'cover': 'Cover your mouth when you cough.',
    'create': 'Let\'s create something new.',
    'cross': 'Look both ways before you cross the street.',
    'cry': 'The baby started to cry.',
    'cut': 'Cut the paper along the dotted line.',
    'damage': 'The storm damaged many houses.',
    'dance': 'Do you know how to dance?',
    'dare': 'I dare you to jump in the pool.',
    'deal with': 'How do you deal with difficult problems?',
    'decide': 'I can\'t decide what to wear.',
    'delete': 'Delete the wrong answer.',
    'deliver': 'The postman will deliver the package.',
    'demand': 'The workers demand better pay.',
    'deny': 'He denied breaking the window.',
    'depend on': 'The picnic depends on the weather.',
    'it depends': 'Will you come? It depends.',
    'describe': 'Can you describe your room?',
    'deserve': 'You deserve a reward for your hard work.',
    'destroy': 'The fire destroyed the building.',
    'develop': 'Children develop at different speeds.',
    'die': 'The flowers will die without water.',
    'dig': 'The dog loves to dig holes.',
    'disappear': 'The magician made the coin disappear.',
    'discover': 'Columbus discovered America in 1492.',
    'discuss': 'Let\'s discuss the plan.',
    'divide': 'Divide the cake into eight pieces.',
    'do': 'I have a lot of work to do.',
    'to do with': 'This has nothing to do with you.',
    'draw': 'I like to draw pictures.',
    'dream': 'I dream of becoming a pilot.',
    'dress': 'Get dressed quickly.',
    'drink': 'Drink plenty of water.',
    'drive': 'My father drives me to school.',
    'drop': 'Don\'t drop the eggs!',
    'drown': 'Be careful not to drown.',
    'earn': 'He earns money by teaching.',
    'eat': 'Let\'s eat dinner together.',
    'encourage': 'My teacher encourages me to try harder.',
    'end': 'The movie will end soon.',
    'enjoy': 'I enjoy playing soccer.',
    'enter': 'Please enter through the main door.',
    'escape': 'The prisoner tried to escape.',
    'examine': 'The doctor will examine you.',
    'except for': 'Everyone came except for Tom.',
    'expect': 'I expect you to be on time.',
    'explain': 'Can you explain this problem to me?',
    'express': 'It\'s important to express your feelings.',
    'face': 'We must face our fears.',
    'fail': 'Don\'t worry if you fail the first time.',
    'fall': 'Be careful not to fall.',
    'fear': 'There is nothing to fear.',
    'feed': 'Don\'t forget to feed the cat.',
    'feel': 'I feel happy today.',
    'feel like': 'I feel like eating pizza.',
    'fight': 'Don\'t fight with your brother.',
    'fill': 'Fill the glass with water.',
    'fill in': 'Fill in the blank spaces.',
    'fill out': 'Please fill out this form.',
    'find': 'I can\'t find my keys.',
    'finish': 'Did you finish your homework?',
    'fit': 'These shoes don\'t fit me.',
    'fix': 'Can you fix my bicycle?',
    'fly': 'Birds can fly in the sky.',
    'follow': 'Follow me, I know the way.',
    'force': 'You can\'t force me to go.',
    'forget': 'Don\'t forget to bring your lunch.',
    'forgive': 'Please forgive me for being late.',
    'form': 'Form a line at the door.',
    'freeze': 'Water freezes at 0 degrees.',
    'fry': 'Fry the eggs in butter.',
    'get': 'I need to get some bread.',
    'get away': 'The thief got away.',
    'get back': 'What time will you get back?',
    'get down': 'Get down from there, it\'s dangerous.',
    'get something down': 'I can\'t get this medicine down.',
    'get off': 'Get off the bus at the next stop.',
    'get on': 'Let\'s get on the train.',
    'get rid of': 'I want to get rid of these old clothes.',
    'get up': 'I get up at 7 every morning.',
    'give': 'Give me your hand.',
    'give in': 'Don\'t give in to pressure.',
    'give out': 'The teacher will give out the papers.',
    'give up': 'Never give up on your dreams.',
    'go': 'Where do you want to go?',
    'go ahead': 'Go ahead, I\'m listening.',
    'go away': 'Go away and leave me alone.',
    'go back': 'Let\'s go back home.',
    'go down': 'The sun goes down in the evening.',
    'go on strike': 'The workers decided to go on strike.',
    'go out': 'Let\'s go out for ice cream.',
    'go shopping': 'Mom goes shopping every Friday.',
    'go up': 'The elevator goes up to the 10th floor.',
    'grow': 'Plants grow in spring.',
    'grow up': 'I want to be a teacher when I grow up.',
    'guess': 'Can you guess my age?',
    'hang': 'Hang your coat on the hook.',
    'happen': 'What happened here?',
    'hate': 'I hate getting up early.',
    'have': 'I have two brothers.',
    'hear': 'Did you hear that noise?',
    'help': 'Can you help me with my homework?',
    'hide': 'Let\'s play hide and seek.',
    'hit': 'Don\'t hit your sister.',
    'hold': 'Hold my hand when we cross the street.',
    'hope': 'I hope you feel better soon.',
    'hurt': 'My leg hurts.',
    'identify': 'Can you identify this plant?',
    'imagine': 'Imagine a world without war.',
    'improve': 'I want to improve my English.',
    'include': 'The price includes breakfast.',
    'increase': 'The population continues to increase.',
    'introduce': 'Let me introduce you to my friend.',
    'invent': 'Who invented the telephone?',
    'invite': 'I\'ll invite all my friends to the party.',
    'join': 'Would you like to join our club?',
    'judge': 'Don\'t judge people by their appearance.',
    'jump': 'How high can you jump?',
    'keep': 'Keep your room tidy.',
    'kick': 'Kick the ball to me.',
    'kill': 'Don\'t kill the insects.',
    'kiss': 'She kissed her baby goodnight.',
    'knock': 'Someone is knocking on the door.',
    'know': 'Do you know the answer?',
    'land': 'The plane will land soon.',
    'last': 'How long does the movie last?',
    'laugh': 'The joke made everyone laugh.',
    'lay': 'Lay the baby down carefully.',
    'lead': 'The guide will lead us through the forest.',
    'lead to': 'This path leads to the beach.',
    'learn': 'I learn something new every day.',
    'leave': 'What time does the bus leave?',
    'lend': 'Can you lend me your eraser?',
    'let': 'Let me help you.',
    'lie': 'Don\'t lie to me.',
    'lift': 'This box is too heavy to lift.',
    'light': 'Light the candles on the cake.',
    'like': 'I like chocolate ice cream.',
    'listen': 'Listen to the teacher carefully.',
    'live': 'I live in a small house.',
    'lock': 'Don\'t forget to lock the door.',
    'look': 'Look at that beautiful bird!',
    'look after': 'I look after my little sister.',
    'look for': 'I\'m looking for my glasses.',
    'look forward to': 'I look forward to seeing you.',
    'look like': 'You look like your mother.',
    'look up': 'Look up the word in the dictionary.',
    'lose': 'I don\'t want to lose this game.',
    'love': 'I love my family.',
    'mail': 'I need to mail this letter.',
    'make': 'Let\'s make a cake.',
    'make a difference': 'One person can make a difference.',
    'it makes no difference': 'It makes no difference to me.',
    'make an effort': 'You need to make an effort to study.',
    'make sure': 'Make sure you lock the door.',
    'manage to': 'I managed to finish on time.',
    'mark': 'Mark the correct answer.',
    'marry': 'They will marry next year.',
    'match': 'These socks don\'t match.',
    'matter': 'What\'s the matter?',
    'no matter': 'I\'ll be there no matter what.',
    'mean': 'What does this word mean?',
    'measure': 'Measure the length of the table.',
    'meet': 'Let\'s meet at the park.',
    'melt': 'The ice cream is melting.',
    'mention': 'Don\'t mention this to anyone.',
    'mind': 'I don\'t mind waiting.',
    'I don\'t mind': 'I don\'t mind if you open the window.',
    'do you mind': 'Do you mind closing the door?',
    'never mind': 'Never mind, it\'s not important.',
    'miss': 'I miss my grandmother.',
    'mix': 'Mix the flour and sugar together.',
    'move': 'Don\'t move, stay still.',
    'need': 'I need a new pencil.',
    'notice': 'Did you notice anything strange?',
    'obey': 'You must obey the rules.',
    'occur': 'When did the accident occur?',
    'offer': 'He offered to help me.',
    'open': 'Open the window, please.',
    'operate': 'Do you know how to operate this machine?',
    'order': 'Let\'s order pizza for dinner.',
    'organize': 'We need to organize our room.',
    'own': 'I own three bicycles.',
    'pack': 'Pack your suitcase tonight.',
    'paint': 'Let\'s paint the wall blue.',
    'park': 'You can\'t park here.',
    'pass': 'Please pass the salt.',
    'pay': 'How much did you pay for that?',
    'perform': 'The band will perform tonight.',
    'pick': 'Pick a card, any card.',
    'pick up': 'Pick up your toys from the floor.',
    'plan': 'What do you plan to do tomorrow?',
    'plant': 'Let\'s plant some flowers.',
    'play': 'Do you want to play with me?',
    'please': 'Please sit down.',
    'point': 'Don\'t point at people.',
    'polish': 'Polish your shoes before the party.',
    'pour': 'Pour the milk into the glass.',
    'practice': 'I practice piano every day.',
    'praise': 'The teacher praised my work.',
    'pray': 'They pray every evening.',
    'predict': 'Can you predict the future?',
    'prefer': 'I prefer tea to coffee.',
    'prepare': 'Prepare your books for tomorrow.',
    'present': 'She presented her project to the class.',
    'press': 'Press the red button.',
    'pretend': 'Let\'s pretend we\'re astronauts.',
    'prevent': 'How can we prevent accidents?',
    'print': 'Can you print this document?',
    'promise': 'I promise to be good.',
    'pronounce': 'How do you pronounce this word?',
    'protect': 'We must protect the environment.',
    'prove': 'Can you prove you\'re right?',
    'provide': 'The school provides free lunch.',
    'pull': 'Pull the door to open it.',
    'punish': 'Parents shouldn\'t punish children harshly.',
    'push': 'Push the button to start.',
    'put': 'Put your books on the table.',
    'raise': 'Raise your hand if you know the answer.',
    'reach': 'Can you reach that shelf?',
    'read': 'I love to read books.',
    'realize': 'I didn\'t realize it was so late.',
    'receive': 'I received a letter from my friend.',
    'recognize': 'Do you recognize this person?',
    'recommend': 'I recommend this restaurant.',
    'record': 'Let\'s record our voices.',
    'reduce': 'We need to reduce waste.',
    'refuse': 'He refused to help.',
    'relax': 'Relax and enjoy your vacation.',
    'remain': 'Please remain in your seats.',
    'remember': 'Do you remember my name?',
    'remind': 'Remind me to call my mom.',
    'remove': 'Remove your shoes before entering.',
    'repair': 'Can you repair my bike?',
    'repeat': 'Please repeat the question.',
    'replace': 'We need to replace the broken window.',
    'reply': 'Did he reply to your email?',
    'report': 'Report to the office immediately.',
    'request': 'I\'d like to request a day off.',
    'require': 'This job requires hard work.',
    'rescue': 'The firefighters rescued the cat.',
    'respect': 'Respect your elders.',
    'rest': 'You need to rest after running.',
    'return': 'Please return my book when you\'re done.',
    'reveal': 'Don\'t reveal the secret.',
    'review': 'Let\'s review what we learned.',
    'ride': 'I learned to ride a bicycle.',
    'ring': 'The phone is ringing.',
    'rise': 'The sun rises in the east.',
    'rob': 'Someone robbed the bank.',
    'roll': 'Roll the ball to me.',
    'rub': 'Rub your hands together to warm them.',
    'ruin': 'Don\'t ruin your new shoes.',
    'rule': 'The king ruled for 50 years.',
    'run': 'I can run very fast.',
    'rush': 'Don\'t rush, we have plenty of time.',
    'sail': 'We\'ll sail across the lake.',
    'satisfy': 'Nothing satisfies him.',
    'save': 'Save your money for something special.',
    'save money': 'I\'m trying to save money for a bike.',
    'save time': 'This shortcut will save time.',
    'say': 'What did you say?',
    'scare': 'Don\'t scare your little brother.',
    'scream': 'Don\'t scream, use your indoor voice.',
    'search': 'Help me search for my keys.',
    'see': 'I can see a rainbow.',
    'seem': 'You seem tired today.',
    'sell': 'They sell fresh vegetables.',
    'send': 'Send me a message later.',
    'separate': 'Separate the white clothes from the colored.',
    'serve': 'Dinner is served at 6 PM.',
    'set': 'Set the table for dinner.',
    'set up': 'Let\'s set up the tent.',
    'settle': 'Settle down and start working.',
    'shake': 'Shake the bottle before opening.',
    'share': 'Share your toys with your sister.',
    'shine': 'The stars shine at night.',
    'shoot': 'Don\'t shoot at people.',
    'shop': 'I need to shop for groceries.',
    'shout': 'Don\'t shout at me!',
    'show': 'Show me your drawing.',
    'shut': 'Shut the window, it\'s cold.',
    'sing': 'She sings beautifully.',
    'sit': 'Please sit here.',
    'ski': 'I learned to ski last winter.',
    'sleep': 'I sleep eight hours every night.',
    'smell': 'These flowers smell wonderful.',
    'smile': 'Smile for the camera!',
    'smoke': 'Smoking is bad for your health.',
    'snow': 'Look, it\'s snowing!',
    'solve': 'Can you solve this puzzle?',
    'sort': 'Sort the cards by color.',
    'sort of': 'I\'m sort of hungry.',
    'sort out': 'Let\'s sort out this problem.',
    'sound': 'That sounds like a good idea.',
    'speak': 'Do you speak English?',
    'spell': 'How do you spell your name?',
    'spend': 'Don\'t spend all your money.',
    'spend money': 'She spends money on books.',
    'spend time': 'I love to spend time with family.',
    'spill': 'Don\'t spill the juice.',
    'stand': 'Please stand up.',
    'start': 'Let\'s start the game.',
    'state': 'Please state your name.',
    'stay': 'Stay here while I\'m gone.',
    'steal': 'It\'s wrong to steal.',
    'stick': 'Stick the stamp on the envelope.',
    'stop': 'Stop making noise!',
    'store': 'Store the food in the fridge.',
    'strike': 'The clock struck twelve.',
    'study': 'I study English every day.',
    'succeed in': 'I succeeded in passing the test.',
    'suggest': 'I suggest we leave early.',
    'suit': 'This job suits you perfectly.',
    'supply': 'The store supplies everything we need.',
    'support': 'My family supports me.',
    'suppose': 'I suppose you\'re right.',
    'surprise': 'Let\'s surprise Mom with a gift.',
    'survive': 'How did you survive the cold?',
    'suspect': 'I suspect he\'s lying.',
    'swim': 'I love to swim in the sea.',
    'swing': 'Push me on the swing!',
    'switch off': 'Switch off the light when you leave.',
    'switch on': 'Switch on the TV, please.',
    'take': 'Take an umbrella, it might rain.',
    'take care of': 'I take care of my dog.',
    'take into account': 'We must take into account all the facts.',
    'take part in': 'I will take part in the race.',
    'take place': 'The wedding will take place in June.',
    'talk': 'Stop talking and listen.',
    'taste': 'Taste the soup and tell me if it needs salt.',
    'teach': 'My father teaches math.',
    'tear': 'Don\'t tear the paper.',
    'tell': 'Tell me a story.',
    'tend to': 'Children tend to ask many questions.',
    'test': 'We have a test tomorrow.',
    'thank': 'Thank you for your help.',
    'think': 'What do you think about this?',
    'throw': 'Throw the ball to me.',
    'throw away': 'Don\'t throw away good food.',
    'throw out': 'Let\'s throw out the garbage.',
    'tie': 'Tie your shoelaces.',
    'touch': 'Don\'t touch the hot stove.',
    'train': 'He trains every day for the competition.',
    'translate': 'Can you translate this to Hebrew?',
    'travel': 'I love to travel to new places.',
    'treat': 'Treat others with kindness.',
    'trust': 'I trust you to keep my secret.',
    'try': 'Try your best on the test.',
    'turn': 'Turn right at the next corner.',
    'type': 'Can you type fast?',
    'understand': 'Do you understand the lesson?',
    'use': 'Use a pencil to write.',
    'used to': 'I used to live in Tel Aviv.',
    'be used to': 'I am used to waking up early.',
    'visit': 'Let\'s visit grandma this weekend.',
    'vote': 'Citizens vote for their leaders.',
    'wait': 'Wait for me at the entrance.',
    'wake up': 'I wake up at 7 o\'clock.',
    'walk': 'I walk to school every day.',
    'want': 'I want a new bicycle.',
    'warn': 'I warned you not to touch it.',
    'wash': 'Wash your hands before eating.',
    'waste': 'Don\'t waste water.',
    'watch': 'Let\'s watch a movie tonight.',
    'wave': 'The children waved goodbye.',
    'wear': 'What are you going to wear?',
    'weigh': 'How much do you weigh?',
    'welcome': 'Welcome to our home!',
    'win': 'I hope our team wins.',
    'wish': 'I wish you a happy birthday.',
    'wonder': 'I wonder what time it is.',
    'work': 'My parents work hard.',
    'worry': 'Don\'t worry, everything will be fine.',
    'write': 'Write your name at the top.',
    'write down': 'Write down the homework.',
    'yell': 'Don\'t yell in the library.',

    # Nouns - People
    'adult': 'An adult is a person over 18 years old.',
    'baby': 'The baby is sleeping.',
    'boy': 'The boy is playing in the park.',
    'brother': 'I have one younger brother.',
    'child': 'Every child deserves a good education.',
    'children': 'The children are playing outside.',
    'cousin': 'My cousin lives in Haifa.',
    'dad': 'My dad drives me to school.',
    'daughter': 'She has two daughters.',
    'family': 'I love my family very much.',
    'father': 'My father is a doctor.',
    'friend': 'Sarah is my best friend.',
    'girl': 'The girl is wearing a red dress.',
    'grandfather': 'My grandfather tells funny stories.',
    'grandmother': 'Grandmother makes delicious cookies.',
    'guy': 'That guy is really funny.',
    'husband': 'Her husband is a teacher.',
    'kid': 'The kid is playing with toys.',
    'lady': 'That lady helped me find my way.',
    'man': 'The man is reading a newspaper.',
    'member': 'He is a member of the basketball team.',
    'mom': 'My mom makes the best pancakes.',
    'mother': 'My mother works at a hospital.',
    'parent': 'Every parent wants the best for their child.',
    'partner': 'My partner and I work well together.',
    'passenger': 'All passengers must fasten their seatbelts.',
    'people': 'Many people came to the party.',
    'person': 'She is a kind person.',
    'police officer': 'The police officer helped us cross the street.',
    'pupil': 'Every pupil has a desk.',
    'sister': 'My sister is older than me.',
    'son': 'They have one son.',
    'student': 'Every student must do homework.',
    'teacher': 'My teacher is very nice.',
    'teenager': 'My brother is a teenager.',
    'teen': 'The mall is full of teens.',
    'wife': 'His wife is a nurse.',
    'woman': 'The woman is wearing a blue coat.',
    'worker': 'The workers built a new bridge.',

    # Nouns - Animals
    'animal': 'My favorite animal is a dolphin.',
    'bird': 'A bird is building a nest in the tree.',
    'cat': 'My cat sleeps all day.',
    'cow': 'The cow gives us milk.',
    'dog': 'My dog loves to play fetch.',
    'dolphin': 'We saw dolphins at the beach.',
    'donkey': 'The donkey carried the heavy load.',
    'elephant': 'The elephant has a long trunk.',
    'fish': 'We have colorful fish in our tank.',
    'horse': 'I learned to ride a horse.',
    'lion': 'The lion is the king of the jungle.',
    'monkey': 'The monkeys are swinging in the trees.',
    'mouse': 'A mouse ran across the floor.',
    'pet': 'Do you have any pets?',
    'rabbit': 'The rabbit is eating carrots.',
    'sheep': 'The farmer has many sheep.',
    'tiger': 'Tigers have beautiful stripes.',

    # Nouns - Food and Drink
    'apple': 'An apple a day keeps the doctor away.',
    'banana': 'I eat a banana for breakfast.',
    'bread': 'Can you buy some bread?',
    'breakfast': 'Breakfast is the most important meal.',
    'cake': 'Mom baked a chocolate cake.',
    'candy': 'Too much candy is bad for your teeth.',
    'cheese': 'I like cheese on my sandwich.',
    'chicken': 'We\'re having chicken for dinner.',
    'chocolate': 'I love chocolate ice cream.',
    'coffee': 'My dad drinks coffee every morning.',
    'cookie': 'May I have a cookie?',
    'cream': 'Add some cream to your coffee.',
    'dinner': 'What\'s for dinner tonight?',
    'drink': 'What would you like to drink?',
    'egg': 'Boil the egg for 10 minutes.',
    'fish': 'Fish is healthy food.',
    'food': 'This restaurant serves delicious food.',
    'fruit': 'Fruit is good for your health.',
    'gram': 'Add 200 grams of flour.',
    'ice cream': 'I want vanilla ice cream.',
    'juice': 'Orange juice is my favorite.',
    'lunch': 'I pack my lunch every day.',
    'meal': 'Enjoy your meal!',
    'meat': 'Some people don\'t eat meat.',
    'milk': 'Drink your milk.',
    'orange': 'Oranges are high in vitamin C.',
    'pizza': 'Let\'s order pizza tonight.',
    'rice': 'We eat rice with the curry.',
    'salt': 'Pass the salt, please.',
    'sandwich': 'I made a cheese sandwich.',
    'snack': 'I need a snack before practice.',
    'soup': 'Chicken soup is good when you\'re sick.',
    'sugar': 'Don\'t add too much sugar.',
    'tea': 'Would you like some tea?',
    'vegetable': 'Eat your vegetables.',
    'water': 'Drink plenty of water every day.',

    # Nouns - Places
    'airport': 'The airport is very busy today.',
    'apartment': 'They live in a small apartment.',
    'bank': 'I need to go to the bank.',
    'beach': 'Let\'s go to the beach this weekend.',
    'bedroom': 'My bedroom is upstairs.',
    'building': 'That building is 50 stories tall.',
    'cafeteria': 'The school cafeteria serves lunch.',
    'castle': 'The old castle is now a museum.',
    'church': 'The church has beautiful windows.',
    'cinema': 'There\'s a new movie at the cinema.',
    'city': 'New York is a big city.',
    'class': 'Our class has 25 students.',
    'classroom': 'Keep the classroom clean.',
    'clinic': 'The clinic opens at 8 AM.',
    'club': 'I joined the chess club.',
    'coast': 'We drove along the coast.',
    'college': 'She goes to college in Jerusalem.',
    'corner': 'The store is on the corner.',
    'country': 'Israel is a beautiful country.',
    'desert': 'The desert is very hot and dry.',
    'door': 'Close the door behind you.',
    'earth': 'The earth is round.',
    'field': 'The children are playing in the field.',
    'floor': 'Don\'t sit on the floor.',
    'forest': 'Many animals live in the forest.',
    'garden': 'We grow tomatoes in our garden.',
    'ground': 'The ball fell to the ground.',
    'home': 'There\'s no place like home.',
    'hospital': 'My sister was born in this hospital.',
    'hotel': 'We stayed in a nice hotel.',
    'house': 'They bought a new house.',
    'island': 'Hawaii is made of many islands.',
    'kitchen': 'Mom is cooking in the kitchen.',
    'library': 'You must be quiet in the library.',
    'market': 'The market is crowded on Fridays.',
    'mountain': 'That mountain is very high.',
    'museum': 'The museum has ancient artifacts.',
    'office': 'My father works in an office.',
    'park': 'The park has a nice playground.',
    'place': 'This is a nice place to live.',
    'playground': 'The playground has swings and slides.',
    'restaurant': 'Let\'s eat at that Italian restaurant.',
    'river': 'The river flows into the sea.',
    'road': 'This road leads to the city.',
    'room': 'My room is painted blue.',
    'school': 'I go to school every day.',
    'sea': 'The Mediterranean Sea is beautiful.',
    'shop': 'That shop sells shoes.',
    'station': 'The bus station is near my house.',
    'store': 'The store closes at 8 PM.',
    'street': 'What street do you live on?',
    'town': 'Our town has 5,000 people.',
    'village': 'My grandmother lives in a small village.',
    'wall': 'Hang the picture on the wall.',
    'window': 'Open the window, it\'s hot.',
    'world': 'I want to travel around the world.',
    'yard': 'The children are playing in the yard.',

    # Nouns - Objects and Things
    'bag': 'Put your books in your bag.',
    'ball': 'Throw the ball to me.',
    'bed': 'Make your bed every morning.',
    'bell': 'The bell rings at 3 o\'clock.',
    'belt': 'Fasten your seat belt.',
    'bicycle': 'I ride my bicycle to school.',
    'bike': 'Let\'s go for a bike ride.',
    'blanket': 'This blanket is warm and soft.',
    'boat': 'We went fishing in a small boat.',
    'book': 'This book is very interesting.',
    'bottle': 'Drink the whole bottle of water.',
    'box': 'The box is full of toys.',
    'bridge': 'The bridge crosses the river.',
    'brush': 'Brush your teeth twice a day.',
    'button': 'Push the red button.',
    'cage': 'The bird is in a cage.',
    'calculator': 'Use a calculator for math.',
    'calendar': 'Mark the date on the calendar.',
    'camera': 'Take a picture with your camera.',
    'candle': 'Light the candles on the cake.',
    'cap': 'He\'s wearing a baseball cap.',
    'card': 'I got a birthday card from grandma.',
    'carpet': 'The carpet is soft under my feet.',
    'case': 'Put the glasses in the case.',
    'chair': 'Sit on the chair.',
    'clock': 'The clock says it\'s 3 PM.',
    'clothes': 'Hang your clothes in the closet.',
    'coat': 'Wear your coat, it\'s cold outside.',
    'coin': 'I found a coin on the ground.',
    'computer': 'I use my computer for homework.',
    'cup': 'Would you like a cup of tea?',
    'cupboard': 'The plates are in the cupboard.',
    'curtain': 'Close the curtains, it\'s too bright.',
    'desk': 'My desk is covered with books.',
    'dish': 'Wash the dishes after dinner.',
    'doll': 'She got a new doll for her birthday.',
    'dress': 'She wore a beautiful dress.',
    'file': 'Save the file on your computer.',
    'furniture': 'They bought new furniture.',
    'game': 'Let\'s play a game.',
    'glass': 'Be careful with the glass.',
    'glove': 'Wear gloves, it\'s cold.',
    'gun': 'Guns are dangerous.',
    'hammer': 'Use a hammer to hit the nail.',
    'hat': 'He\'s wearing a funny hat.',
    'helicopter': 'The helicopter landed on the roof.',
    'key': 'I lost my house key.',
    'knife': 'Cut the bread with a knife.',
    'lamp': 'Turn on the lamp, it\'s dark.',
    'letter': 'I received a letter from my friend.',
    'light': 'Turn off the light when you leave.',
    'machine': 'This machine makes coffee.',
    'magazine': 'I read a science magazine.',
    'map': 'Use a map to find your way.',
    'match': 'Be careful with matches.',
    'mirror': 'Look at yourself in the mirror.',
    'model': 'He built a model airplane.',
    'money': 'Money can\'t buy happiness.',
    'needle': 'Thread the needle carefully.',
    'notebook': 'Write your homework in your notebook.',
    'page': 'Turn to page 24.',
    'paper': 'Write your name on the paper.',
    'pen': 'Can I borrow your pen?',
    'pencil': 'Use a pencil for the test.',
    'phone': 'My phone is ringing.',
    'picture': 'Draw a picture of your house.',
    'piece': 'May I have a piece of cake?',
    'plate': 'Put your food on the plate.',
    'present': 'I got many presents for my birthday.',
    'presents': 'The presents are under the tree.',
    'prize': 'She won first prize.',
    'project': 'My science project is about plants.',
    'puzzle': 'This puzzle has 500 pieces.',
    'ring': 'She has a gold ring.',
    'rock': 'Don\'t throw rocks.',
    'rope': 'Tie it with a rope.',
    'ruler': 'Use a ruler to draw straight lines.',
    'scissors': 'Cut the paper with scissors.',
    'screen': 'The screen is too bright.',
    'seat': 'Please take a seat.',
    'shoe': 'My shoe is untied.',
    'shoes': 'Take off your shoes.',
    'soap': 'Wash your hands with soap.',
    'sock': 'I can\'t find my other sock.',
    'spoon': 'Stir the soup with a spoon.',
    'stick': 'The dog fetched the stick.',
    'stone': 'The stone is smooth and round.',
    'table': 'Set the table for dinner.',
    'ticket': 'I bought tickets for the concert.',
    'tool': 'Use the right tool for the job.',
    'toy': 'Clean up your toys.',
    'train': 'The train leaves at 8 AM.',
    'trash': 'Take out the trash.',
    'treasure': 'The pirates found the treasure.',
    'truck': 'The truck is carrying furniture.',
    'umbrella': 'Take an umbrella, it might rain.',
    'vase': 'Put the flowers in a vase.',
    'watch': 'What time is it on your watch?',
    'wheel': 'The car has four wheels.',

    # Nouns - Body parts
    'arm': 'He broke his arm.',
    'back': 'My back hurts.',
    'blood': 'The nurse took a blood sample.',
    'body': 'Your body needs rest.',
    'bone': 'He broke a bone in his leg.',
    'brain': 'Use your brain to solve problems.',
    'ear': 'I can\'t hear with this ear.',
    'eye': 'She has beautiful blue eyes.',
    'face': 'Wash your face every morning.',
    'finger': 'I cut my finger.',
    'foot': 'My foot hurts.',
    'hair': 'She has long brown hair.',
    'hand': 'Wash your hands before eating.',
    'head': 'I have a headache.',
    'headache': 'Take medicine for your headache.',
    'heart': 'Exercise is good for your heart.',
    'leg': 'He injured his leg playing soccer.',
    'mouth': 'Open your mouth and say \"ah\".',
    'nose': 'My nose is runny.',
    'skin': 'Protect your skin from the sun.',
    'stomach': 'My stomach hurts.',
    'tooth': 'I lost a tooth.',
    'voice': 'She has a beautiful voice.',

    # Nouns - Nature
    'air': 'The air is fresh in the morning.',
    'beach': 'Let\'s build a sandcastle at the beach.',
    'cloud': 'The clouds are white and fluffy.',
    'fire': 'Be careful with fire.',
    'flower': 'This flower smells nice.',
    'grass': 'The grass is green.',
    'heat': 'I can\'t stand this heat.',
    'ice': 'The ice is melting.',
    'lake': 'We went swimming in the lake.',
    'leaf': 'The leaves change color in fall.',
    'moon': 'The moon is bright tonight.',
    'nature': 'I love being in nature.',
    'ocean': 'The ocean is deep and mysterious.',
    'plant': 'Water the plants every day.',
    'rain': 'The rain is falling heavily.',
    'rock': 'We climbed over the rocks.',
    'sand': 'The sand is hot on my feet.',
    'sky': 'Look at the beautiful sky.',
    'snow': 'The snow is falling softly.',
    'star': 'The stars are bright tonight.',
    'stone': 'Smooth stones line the path.',
    'sun': 'The sun is shining today.',
    'tree': 'The tree is 100 years old.',
    'water': 'Plants need water to grow.',
    'wave': 'Big waves crashed on the beach.',
    'weather': 'The weather is nice today.',
    'wind': 'The wind is blowing hard.',
    'wood': 'The table is made of wood.',

    # Nouns - Time
    'afternoon': 'See you this afternoon.',
    'age': 'What is your age?',
    'autumn': 'The leaves fall in autumn.',
    'birthday': 'Happy birthday!',
    'century': 'A century is 100 years.',
    'date': 'What\'s today\'s date?',
    'date of birth': 'Please write your date of birth.',
    'day': 'Have a nice day!',
    'evening': 'Good evening!',
    'future': 'Think about your future.',
    'history': 'History is my favorite subject.',
    'holiday': 'We\'re going on holiday next week.',
    'hour': 'The movie lasts two hours.',
    'minute': 'Wait a minute, please.',
    'month': 'June is my favorite month.',
    'morning': 'Good morning!',
    'night': 'Good night, sleep well.',
    'past': 'Don\'t worry about the past.',
    'present': 'Live in the present moment.',
    'season': 'Summer is my favorite season.',
    'second': 'Wait a second!',
    'spare time': 'What do you do in your spare time?',
    'spring': 'Flowers bloom in spring.',
    'summer': 'We go swimming in summer.',
    'time': 'What time is it?',
    'today': 'What are you doing today?',
    'tomorrow': 'See you tomorrow.',
    'vacation': 'We\'re going on vacation.',
    'week': 'There are seven days in a week.',
    'weekend': 'What are your plans for the weekend?',
    'winter': 'It\'s cold in winter.',
    'year': 'This year went by quickly.',
    'yesterday': 'Where were you yesterday?',

    # Nouns - Abstract
    'ability': 'She has the ability to learn quickly.',
    'accident': 'He had an accident on his bike.',
    'account': 'Open a bank account.',
    'in any case': 'In any case, I\'ll be there.',
    'activity': 'Soccer is a popular activity.',
    'advantage': 'What\'s the advantage of this plan?',
    'adventure': 'Life is an adventure.',
    'advice': 'Can you give me some advice?',
    'alarm': 'Set the alarm for 6 AM.',
    'announcement': 'The principal made an announcement.',
    'answer': 'I don\'t know the answer.',
    'appearance': 'Don\'t judge people by their appearance.',
    'argument': 'They had an argument.',
    'arrangement': 'We made arrangements for the party.',
    'art': 'Art class is fun.',
    'article': 'I read an article about space.',
    'as...as': 'She is as tall as her brother.',
    'assessment': 'The teacher gave us an assessment.',
    'attention': 'Pay attention in class.',
    'award': 'She won an award for her painting.',
    'basis': 'Exercise should be part of your daily basis.',
    'battle': 'The battle lasted three days.',
    'behavior': 'Good behavior is important.',
    'belief': 'Everyone has their own beliefs.',
    'border': 'We crossed the border into Jordan.',
    'bottom': 'The answer is at the bottom of the page.',
    'branch': 'The bank has many branches.',
    'business': 'My parents own a small business.',
    'capital': 'Jerusalem is the capital of Israel.',
    'care': 'Take care of your belongings.',
    'cartoon': 'I love watching cartoons.',
    'cash': 'I don\'t have any cash.',
    'celebration': 'We\'re having a celebration tonight.',
    'chance': 'Give me another chance.',
    'change': 'Change is not always easy.',
    'chapter': 'Read chapter 5 for homework.',
    'character': 'He is an interesting character.',
    'in charge of': 'Who is in charge of this project?',
    'choice': 'You have to make a choice.',
    'circle': 'Draw a circle on the paper.',
    'code': 'What\'s the secret code?',
    'color': 'My favorite color is blue.',
    'communication': 'Good communication is important.',
    'company': 'My father works for a big company.',
    'condition': 'The old car is in bad condition.',
    'on condition that': 'You can go on condition that you finish homework.',
    'under control': 'The situation is under control.',
    'connection': 'There\'s a connection between these events.',
    'contents': 'Check the table of contents.',
    'conversation': 'We had a nice conversation.',
    'corner': 'The shop is around the corner.',
    'course': 'I\'m taking a cooking course.',
    'I took a course': 'I took a course in photography.',
    'crime': 'Stealing is a crime.',
    'crowd': 'There was a big crowd at the concert.',
    'culture': 'Every country has its own culture.',
    'dance': 'May I have this dance?',
    'danger': 'Danger! Do not enter.',
    'in danger': 'The animals are in danger.',
    'deal': 'That\'s a good deal.',
    'death': 'We were sad about his death.',
    'decision': 'I made an important decision.',
    'definition': 'Look up the definition in the dictionary.',
    'description': 'Give me a description of the thief.',
    'detail': 'Tell me every detail.',
    'difference': 'What\'s the difference between these two?',
    'difficulty': 'We had difficulty finding the place.',
    'dinner': 'Dinner is ready!',
    'direction': 'Go in that direction.',
    'director': 'The director made a great movie.',
    'discussion': 'We had a long discussion.',
    'doubt': 'I have no doubt about it.',
    'no doubt': 'No doubt she will win.',
    'drama': 'We\'re studying drama at school.',
    'dream': 'I had a strange dream last night.',
    'education': 'Education is very important.',
    'effect': 'The medicine had no effect.',
    'effort': 'You need to make an effort.',
    'election': 'The election is next month.',
    'end': 'This is the end of the story.',
    'energy': 'I have no energy today.',
    'engine': 'The car engine is broken.',
    'environment': 'We must protect the environment.',
    'error': 'There\'s an error in this sentence.',
    'event': 'The party was a big event.',
    'examination': 'We have an examination tomorrow.',
    'example': 'Can you give me an example?',
    'experience': 'I had an amazing experience.',
    'expert': 'He\'s an expert in computers.',
    'explanation': 'I need an explanation.',
    'fact': 'It\'s a fact that water boils at 100 degrees.',
    'failure': 'Don\'t be afraid of failure.',
    'fear': 'He has a fear of heights.',
    'festival': 'There\'s a music festival this weekend.',
    'fight': 'They had a fight.',
    'form': 'Fill out this form.',
    'freedom': 'Everyone wants freedom.',
    'fun': 'We had so much fun!',
    'game': 'Let\'s play a game.',
    'gas': 'The car needs gas.',
    'goal': 'My goal is to become a teacher.',
    'government': 'The government makes the laws.',
    'grammar': 'English grammar is difficult.',
    'graph': 'Draw a graph of the results.',
    'habit': 'Reading is a good habit.',
    'health': 'Good health is important.',
    'help': 'Thank you for your help.',
    'hint': 'Give me a hint.',
    'hobby': 'Reading is my hobby.',
    'hope': 'I have hope for the future.',
    'idea': 'That\'s a great idea!',
    'no idea': 'I have no idea what you mean.',
    'identity': 'Show me your identity card.',
    'importance': 'She explained the importance of exercise.',
    'increase': 'There was an increase in prices.',
    'information': 'I need more information.',
    'for instance': 'Many animals, for instance dogs and cats, are pets.',
    'instead of': 'Let\'s walk instead of taking the bus.',
    'interview': 'I have a job interview tomorrow.',
    'invitation': 'Thanks for the invitation.',
    'issue': 'Climate change is an important issue.',
    'item': 'This item is on sale.',
    'job': 'My dad has a new job.',
    'joke': 'He told a funny joke.',
    'journey': 'Have a safe journey!',
    'joy': 'She was filled with joy.',
    'knowledge': 'Knowledge is power.',
    'language': 'How many languages do you speak?',
    'law': 'Breaking the law is wrong.',
    'leader': 'He\'s a natural leader.',
    'lesson': 'Today\'s lesson is about plants.',
    'level': 'What level are you at?',
    'life': 'Life is beautiful.',
    'limit': 'There\'s a speed limit on this road.',
    'limited to': 'Entry is limited to 50 people.',
    'line': 'Draw a straight line.',
    'link': 'There\'s a link between smoking and cancer.',
    'list': 'Make a list of things to buy.',
    'literature': 'We study English literature.',
    'load': 'That\'s a heavy load to carry.',
    'loss': 'The team suffered a loss.',
    'love': 'Love makes the world go round.',
    'luck': 'Good luck on your test!',
    'mark': 'What mark did you get?',
    'material': 'What material is this made of?',
    'math': 'Math is my favorite subject.',
    'maths': 'I\'m good at maths.',
    'maximum': 'The maximum speed is 50 km/h.',
    'meaning': 'What\'s the meaning of this word?',
    'message': 'I got your message.',
    'method': 'What\'s the best method for studying?',
    'middle': 'Put it in the middle of the table.',
    'minimum': 'The minimum age is 12.',
    'mistake': 'Everyone makes mistakes.',
    'model': 'She is a fashion model.',
    'music': 'I love listening to music.',
    'name': 'What\'s your name?',
    'nation': 'Israel is a small nation.',
    'news': 'Did you hear the news?',
    'newspaper': 'My dad reads the newspaper.',
    'noise': 'Please don\'t make noise.',
    'note': 'I left you a note.',
    'number': 'What\'s your phone number?',
    'object': 'What is that strange object?',
    'opinion': 'What\'s your opinion?',
    'in my opinion': 'In my opinion, we should leave now.',
    'opportunity': 'This is a great opportunity.',
    'order': 'Please put these in order.',
    'in order to': 'Study hard in order to succeed.',
    'operation': 'She needs an operation.',
    'pain': 'I\'m in terrible pain.',
    'paragraph': 'Write a paragraph about your family.',
    'party': 'Are you going to the party?',
    'pattern': 'I see a pattern in these numbers.',
    'peace': 'We all want peace.',
    'period': 'We have a 40-minute period.',
    'permission': 'Do I have your permission?',
    'photo': 'Take a photo of me.',
    'photograph': 'That\'s a beautiful photograph.',
    'plan': 'What\'s the plan for today?',
    'pleasure': 'It\'s a pleasure to meet you.',
    'point': 'What\'s your point?',
    'point of view': 'From my point of view, you\'re wrong.',
    'police': 'Call the police!',
    'population': 'The population is growing.',
    'position': 'She\'s in a difficult position.',
    'possible': 'Is it possible to finish today?',
    'power': 'The king has great power.',
    'practice': 'Practice makes perfect.',
    'pressure': 'I\'m under a lot of pressure.',
    'price': 'What\'s the price of this shirt?',
    'print': 'The book is now in print.',
    'private': 'This is private property.',
    'problem': 'I have a problem.',
    'no problem': 'Can you help? No problem!',
    'process': 'Learning is a slow process.',
    'program': 'What\'s your favorite TV program?',
    'progress': 'You\'re making good progress.',
    'project': 'Our class project is about recycling.',
    'promise': 'I made a promise to help.',
    'proof': 'Do you have proof?',
    'purpose': 'What\'s the purpose of this meeting?',
    'on purpose': 'Did you do that on purpose?',
    'quality': 'This shirt is good quality.',
    'quantity': 'We need a large quantity.',
    'quarter': 'A quarter of the students are absent.',
    'question': 'I have a question.',
    'race': 'Let\'s have a race!',
    'railway': 'The railway connects all the cities.',
    'railroad': 'The railroad was built in 1850.',
    'rate': 'The success rate is high.',
    'reading': 'Reading is important for learning.',
    'reason': 'What\'s the reason for being late?',
    'record': 'He broke the world record.',
    'relationship': 'They have a good relationship.',
    'religion': 'There are many religions in the world.',
    'reply': 'I\'m waiting for your reply.',
    'report': 'Write a report about your trip.',
    'request': 'I have a special request.',
    'research': 'She does research on animals.',
    'respect': 'Treat everyone with respect.',
    'responsible for': 'Who is responsible for this mess?',
    'responsibility': 'It\'s your responsibility.',
    'the rest': 'I\'ll do the rest tomorrow.',
    'result': 'The result was surprising.',
    'as a result of': 'As a result of the rain, the game was canceled.',
    'review': 'I wrote a book review.',
    'right': 'You have the right to say no.',
    'risk': 'Don\'t take unnecessary risks.',
    'role': 'What role did you play?',
    'rule': 'Follow the rules.',
    'safe': 'It\'s safe to cross now.',
    'safety': 'Safety is our priority.',
    'sale': 'There\'s a sale at the store.',
    'on sale': 'These shoes are on sale.',
    'schedule': 'Check your schedule.',
    'science': 'Science is fascinating.',
    'score': 'What was the final score?',
    'secret': 'Can you keep a secret?',
    'sense': 'That doesn\'t make sense.',
    'sentence': 'Write a sentence using this word.',
    'series': 'This is my favorite TV series.',
    'service': 'The service at this restaurant is excellent.',
    'set': 'I got a new set of pens.',
    'shape': 'What shape is this?',
    'shirt': 'He\'s wearing a blue shirt.',
    'shopping': 'I hate shopping.',
    'sign': 'Read the sign.',
    'signal': 'Wait for my signal.',
    'silence': 'There was complete silence.',
    'silver': 'This ring is made of silver.',
    'similar to': 'This is similar to the other one.',
    'singer': 'She wants to be a singer.',
    'single': 'I don\'t have a single dollar.',
    'site': 'This is a construction site.',
    'situation': 'The situation is getting worse.',
    'size': 'What size do you wear?',
    'skill': 'Reading is an important skill.',
    'smell': 'What\'s that smell?',
    'smile': 'She has a beautiful smile.',
    'so that': 'Study hard so that you can succeed.',
    'and so on': 'Bring pens, pencils, erasers, and so on.',
    'social': 'Humans are social creatures.',
    'society': 'We live in a modern society.',
    'solution': 'What\'s the solution to this problem?',
    'song': 'Let\'s sing a song.',
    'sound': 'I heard a strange sound.',
    'south': 'They live in the south.',
    'space': 'There\'s no space left.',
    'speech': 'The principal gave a speech.',
    'speed': 'Reduce your speed.',
    'sport': 'Soccer is my favorite sport.',
    'spot': 'This is a nice spot for a picnic.',
    'stage': 'The actors came on stage.',
    'the first stage of the game': 'We won the first stage of the game.',
    'standard': 'The food was below standard.',
    'start': 'What time is the start?',
    'state': 'The house is in a bad state.',
    'the State of Israel': 'The State of Israel was established in 1948.',
    'the state of play': 'What\'s the state of play?',
    'statement': 'The police took a statement.',
    'step': 'Take one step at a time.',
    'story': 'Tell me a story.',
    'strength': 'He doesn\'t have the strength to continue.',
    'stress': 'I\'m under a lot of stress.',
    'strike': 'The workers are on strike.',
    'structure': 'The structure of the building is unsafe.',
    'stuff': 'What\'s all this stuff?',
    'style': 'I like your style.',
    'subject': 'What\'s your favorite subject?',
    'the subject of the article': 'The subject of the article is climate change.',
    'success': 'Hard work leads to success.',
    'suggestion': 'Do you have any suggestions?',
    'suit': 'He\'s wearing a black suit.',
    'support': 'Thank you for your support.',
    'surface': 'The surface is smooth.',
    'surprise': 'What a nice surprise!',
    'surprised': 'I was surprised to see him.',
    'survey': 'We did a survey about favorite foods.',
    'symbol': 'The dove is a symbol of peace.',
    'system': 'The solar system has eight planets.',
    'task': 'Complete the task.',
    'taste': 'This soup has a strange taste.',
    'tax': 'Everyone pays taxes.',
    'team': 'Our team won the game.',
    'technology': 'Technology changes quickly.',
    'temperature': 'The temperature is 30 degrees.',
    'term': 'What does this term mean?',
    'terrible': 'What terrible weather!',
    'test': 'We have a test tomorrow.',
    'text': 'Read the text on page 12.',
    'over there': 'Put it over there.',
    'theirs': 'That car is theirs.',
    'therefore': 'I was sick, therefore I stayed home.',
    'thick': 'The walls are very thick.',
    'thin': 'The paper is too thin.',
    'thing': 'What\'s that thing?',
    'thought': 'I had an interesting thought.',
    'through': 'We walked through the forest.',
    'thousand': 'There were a thousand people there.',
    'title': 'What\'s the title of the book?',
    'ton': 'The car weighs one ton.',
    'tool': 'This is a useful tool.',
    'top': 'Put it on top of the shelf.',
    'topic': 'The topic of today\'s lesson is animals.',
    'total': 'What\'s the total cost?',
    'touch': 'Keep in touch!',
    'in touch with': 'Are you still in touch with your old friends?',
    'tour': 'We went on a tour of the museum.',
    'tradition': 'It\'s a family tradition.',
    'traffic': 'The traffic is terrible today.',
    'translation': 'Read the English translation.',
    'transport': 'Public transport is cheap here.',
    'trick': 'That was a clever trick.',
    'trip': 'We\'re planning a trip to Europe.',
    'trouble': 'Are you in trouble?',
    'truth': 'Tell me the truth.',
    'tune': 'I know that tune.',
    'turn': 'It\'s your turn.',
    'type': 'What type of music do you like?',
    'ugly': 'That\'s an ugly building.',
    'unit': 'A meter is a unit of length.',
    'unless': 'I\'ll go unless it rains.',
    'up to': 'It\'s up to you to decide.',
    'useful': 'That\'s a useful tip.',
    'usual': 'Everything was as usual.',
    'as usual': 'As usual, he was late.',
    'value': 'This ring has great value.',
    'variety': 'The store has a variety of colors.',
    'view': 'The view from here is beautiful.',
    'violence': 'Violence is never the answer.',
    'visit': 'Come for a visit sometime.',
    'volume': 'Turn down the volume.',
    'vote': 'Everyone has the right to vote.',
    'walk (noun)': 'Let\'s go for a walk.',
    'war': 'War is terrible.',
    'warning': 'They gave us a warning.',
    'waste': 'Don\'t waste your time.',
    'way': 'This is the way to school.',
    'on the way': 'I met her on the way home.',
    'weakness': 'Everyone has weaknesses.',
    'wealth': 'Money can\'t buy happiness, but wealth helps.',
    'weight': 'What\'s your weight?',
    'west': 'The sun sets in the west.',
    'whatever': 'Do whatever you want.',
    'which': 'Which one do you prefer?',
    'on the whole': 'On the whole, it was a good day.',
    'the whole': 'I ate the whole pizza.',
    'whose': 'Whose book is this?',
    'wide': 'The river is very wide.',
    'in other words': 'In other words, we failed.',
    'at work': 'Dad is at work right now.',
    'worth...ing': 'This movie is worth watching.',
    'would': 'I would help if I could.',
    'worried about': 'I\'m worried about the test.',
    'yours': 'Is this pen yours?',
    'zero': 'Ten minus ten equals zero.',

    # Adjectives - Descriptions
    'absent': 'Three students are absent today.',
    'absolutely': 'You\'re absolutely right!',
    'afraid': 'Are you afraid of the dark?',
    'against': 'I\'m against this idea.',
    'age': 'What age are you?',
    'ahead': 'Go ahead, I\'ll follow.',
    'alike': 'The twins look alike.',
    'alive': 'The plant is still alive.',
    'all': 'All students must attend.',
    'alone': 'I don\'t like being alone.',
    'almost': 'We\'re almost there.',
    'although': 'I went out although it was raining.',
    'altogether': 'There were ten people altogether.',
    'amazing': 'That was an amazing performance!',
    'among': 'She is popular among her friends.',
    'ancient': 'These are ancient ruins.',
    'angry': 'Why are you angry?',
    'another': 'Would you like another cookie?',
    'any': 'Do you have any questions?',
    'anywhere': 'I can\'t find it anywhere.',
    'any place': 'You can sit at any place.',
    'apart from': 'Everyone came apart from Tom.',
    'around': 'Look around you.',
    'as': 'He works as a teacher.',
    'as soon as': 'Call me as soon as you arrive.',
    'as if': 'He acts as if he knows everything.',
    'asleep': 'The baby is asleep.',
    'at once': 'Come here at once!',
    'available': 'Is this seat available?',
    'awake': 'Are you awake?',
    'aware': 'Are you aware of the problem?',
    'awful': 'What awful weather!',
    'bad': 'That\'s a bad idea.',
    'badly': 'He plays badly.',
    'basic': 'These are the basic rules.',
    'beautiful': 'What a beautiful day!',
    'because': 'I stayed home because I was sick.',
    'before long': 'I\'ll be back before long.',
    'as long as': 'You can stay as long as you want.',
    'no longer': 'I no longer live there.',
    'best': 'She\'s my best friend.',
    'better': 'I feel better today.',
    'between': 'The secret is between you and me.',
    'big': 'That\'s a big house.',
    'black': 'I want the black shoes.',
    'blue': 'The sky is blue.',
    'born': 'I was born in 2012.',
    'both': 'Both answers are correct.',
    'both...and': 'She speaks both English and French.',
    'brave': 'He was very brave.',
    'bright': 'The sun is bright today.',
    'broken': 'The window is broken.',
    'brown': 'He has brown eyes.',
    'busy': 'I\'m too busy to talk.',
    'calm': 'Try to stay calm.',
    'careful': 'Be careful!',
    'careless': 'That was careless of you.',
    'central': 'We live in central Tel Aviv.',
    'certain': 'I\'m certain she will come.',
    'cheap': 'These shoes are cheap.',
    'clean': 'Your room is very clean.',
    'clear': 'The instructions are clear.',
    'close': 'We live close to the school.',
    'closed': 'The door is closed.',
    'cold': 'It\'s cold today.',
    'colorful': 'She wore a colorful dress.',
    'comfortable': 'This chair is comfortable.',
    'common': 'Smith is a common name.',
    'in common': 'We have a lot in common.',
    'complete': 'The list is complete.',
    'completely': 'I completely forgot!',
    'confident': 'She feels confident about the test.',
    'confused': 'I\'m confused.',
    'cool': 'It\'s nice and cool today.',
    'correct': 'Your answer is correct.',
    'could': 'I could help you tomorrow.',
    'creative': 'She is very creative.',
    'crowded': 'The bus was crowded.',
    'cruel': 'Don\'t be cruel to animals.',
    'cultural': 'We visited many cultural sites.',
    'curious': 'I\'m curious about your trip.',
    'curly': 'She has curly hair.',
    'current': 'What\'s the current temperature?',
    'cute': 'What a cute puppy!',
    'daily': 'Exercise is part of my daily routine.',
    'dangerous': 'Swimming here is dangerous.',
    'dark': 'It gets dark early in winter.',
    'dead': 'The plant is dead.',
    'dear': 'Dear Mom and Dad...',
    'deep': 'The water is very deep.',
    'definitely': 'I will definitely be there.',
    'delicious': 'This cake is delicious.',
    'different': 'These two are different.',
    'difficult': 'This question is difficult.',
    'digital': 'We live in a digital world.',
    'direct': 'Is this a direct flight?',
    'dirty': 'Your hands are dirty.',
    'disappointed': 'I was disappointed with the result.',
    'double': 'I ordered a double espresso.',
    'due to': 'The game was canceled due to rain.',
    'during': 'I fell asleep during the movie.',
    'each other': 'They love each other.',
    'early': 'It\'s too early to go.',
    'east': 'The sun rises in the east.',
    'easy': 'This test is easy.',
    'either': 'You can choose either one.',
    'either...or': 'It\'s either yes or no.',
    'electric': 'This is an electric car.',
    'else': 'What else can I do?',
    'empty': 'The room is empty.',
    'enormous': 'That\'s an enormous elephant!',
    'enough': 'Is there enough food?',
    'equal': 'All people are equal.',
    'especially': 'I love all fruits, especially apples.',
    'even': 'Even I can do it.',
    'exact': 'What\'s the exact time?',
    'exactly': 'That\'s exactly what I meant.',
    'excellent': 'Your work is excellent!',
    'except': 'Everyone came except Mary.',
    'excited': 'I\'m excited about the trip.',
    'exciting': 'What an exciting game!',
    'expensive': 'These shoes are too expensive.',
    'extra': 'Do you have extra paper?',
    'extremely': 'I\'m extremely happy.',
    'fair': 'That\'s not fair!',
    'false': 'The statement is false.',
    'familiar': 'Your face looks familiar.',
    'famous': 'He\'s a famous actor.',
    'far': 'How far is it?',
    'as far as': 'As far as I know, he left.',
    'so far': 'So far, everything is good.',
    'fast': 'He runs very fast.',
    'fat': 'The cat is getting fat.',
    'favorite': 'Blue is my favorite color.',
    'few': 'I have a few questions.',
    'final': 'This is the final warning.',
    'finally': 'We finally arrived.',
    'fine': 'I\'m fine, thanks.',
    'first': 'She came first in the race.',
    'fit': 'These shoes fit perfectly.',
    'flat': 'The land is completely flat.',
    'following': 'Answer the following questions.',
    'foreign': 'He speaks a foreign language.',
    'forever': 'I will love you forever.',
    'fortunately': 'Fortunately, no one was hurt.',
    'free': 'The concert is free.',
    'frequently': 'I frequently visit my grandmother.',
    'fresh': 'I love fresh bread.',
    'friendly': 'She is very friendly.',
    'frightening': 'That was a frightening experience.',
    'front': 'Sit in the front row.',
    'full': 'The glass is full.',
    'funny': 'He told a funny joke.',
    'general': 'This is a general rule.',
    'in general': 'In general, I agree with you.',
    'gentle': 'Be gentle with the baby.',
    'glad': 'I\'m glad you came.',
    'golden': 'She has golden hair.',
    'good': 'That\'s a good idea.',
    'grand': 'They live in a grand house.',
    'grateful': 'I\'m grateful for your help.',
    'gray': 'He has gray hair.',
    'great': 'That\'s great news!',
    'green': 'The grass is green.',
    'guilty': 'He felt guilty about lying.',
    'half': 'Cut the apple in half.',
    'handsome': 'He\'s a handsome young man.',
    'happy': 'I\'m very happy today.',
    'hard': 'This test is hard.',
    'hardly': 'I can hardly hear you.',
    'harmful': 'Smoking is harmful.',
    'healthy': 'Eat healthy food.',
    'heavy': 'This box is heavy.',
    'helpful': 'You\'ve been very helpful.',
    'hers': 'The red bike is hers.',
    'high': 'The mountain is very high.',
    'honest': 'He\'s an honest person.',
    'horrible': 'What a horrible smell!',
    'hot': 'It\'s hot today.',
    'however': 'I\'m tired, however I must continue.',
    'huge': 'That\'s a huge building!',
    'hungry': 'I\'m hungry.',
    'ill': 'She\'s ill and can\'t come to school.',
    'important': 'This is very important.',
    'impossible': 'That\'s impossible!',
    'in addition to': 'In addition to English, she speaks French.',
    'in my opinion': 'In my opinion, we should wait.',
    'in particular': 'I like all sports, in particular soccer.',
    'indeed': 'Thank you very much indeed.',
    'independent': 'He\'s an independent person.',
    'individual': 'Each person is an individual.',
    'interested': 'I\'m interested in science.',
    'interesting': 'This book is very interesting.',
    'international': 'This is an international school.',
    'involved with': 'He\'s involved with many projects.',
    'Jewish': 'They celebrate Jewish holidays.',
    'Jew': 'He is a Jew.',
    'keen': 'She\'s keen on sports.',
    'kind': 'She\'s a very kind person.',
    'large': 'This shirt is too large.',
    'last': 'This is my last chance.',
    'late': 'I\'m sorry I\'m late.',
    'later': 'See you later!',
    'latest': 'Have you seen his latest movie?',
    'least': 'He has the least money.',
    'left': 'Turn left at the corner.',
    'less': 'I have less than you.',
    'likely': 'It\'s likely to rain.',
    'be likely to': 'They are likely to win.',
    'little': 'There\'s very little time.',
    'lively': 'The party was very lively.',
    'local': 'Shop at local stores.',
    'lonely': 'I feel lonely.',
    'long': 'It\'s a long journey.',
    'loud': 'The music is too loud.',
    'lovely': 'What a lovely day!',
    'low': 'The table is very low.',
    'lower': 'The lower shelf is empty.',
    'lucky': 'You\'re lucky to have such friends.',
    'mad': 'Are you mad at me?',
    'main': 'What\'s the main idea?',
    'mainly': 'The class is mainly boys.',
    'major': 'This is a major problem.',
    'may': 'You may go now.',
    'maximum': 'The maximum speed is 50.',
    'middle': 'Sit in the middle row.',
    'might': 'It might rain later.',
    'minimum': 'The minimum age is 12.',
    'mine': 'That book is mine.',
    'minor': 'It\'s just a minor problem.',
    'modern': 'We live in modern times.',
    'more': 'Can I have some more?',
    'more and more': 'It gets more and more difficult.',
    'more or less': 'I more or less understand.',
    'Moslem': 'They follow Moslem traditions.',
    'Muslim': 'He is a Muslim.',
    'must': 'You must be quiet.',
    'narrow': 'The street is very narrow.',
    'neat': 'Keep your desk neat.',
    'nearby': 'There\'s a park nearby.',
    'necessary': 'Sleep is necessary for health.',
    'neither...nor': 'It\'s neither hot nor cold.',
    'nervous': 'I feel nervous before tests.',
    'new': 'I got a new bike.',
    'next': 'See you next week.',
    'nice': 'Have a nice day!',
    'normal': 'Everything is normal.',
    'north': 'They live in the north.',
    'not': 'I\'m not ready yet.',
    'not only': 'He\'s not only smart but also kind.',
    'odd': 'That\'s an odd thing to say.',
    'off': 'The light is off.',
    'official': 'This is the official result.',
    'old': 'My grandfather is very old.',
    'on': 'The book is on the table.',
    'on one\'s own': 'I did it on my own.',
    'once': 'I went there once.',
    'one another': 'They help one another.',
    'online': 'You can buy it online.',
    'only': 'I\'m the only child.',
    'onto': 'Jump onto the platform.',
    'open': 'The door is open.',
    'opposite': 'They have opposite opinions.',
    'orange': 'She wore an orange dress.',
    'ordinary': 'It was just an ordinary day.',
    'organized': 'He\'s a very organized person.',
    'original': 'This is the original copy.',
    'other': 'On the other hand...',
    'on the one hand': 'On the one hand, it\'s expensive.',
    'on the other hand': 'On the other hand, it\'s good quality.',
    'ours': 'The blue car is ours.',
    'own': 'I want my own room.',
    'particular': 'Do you want a particular color?',
    'past': 'It\'s half past three.',
    'peaceful': 'The village is quiet and peaceful.',
    'perfect': 'The weather is perfect!',
    'perhaps': 'Perhaps we should wait.',
    'personal': 'That\'s my personal opinion.',
    'physical': 'Physical exercise is important.',
    'plain': 'I like plain yogurt.',
    'pleasant': 'What a pleasant surprise!',
    'pleased': 'I\'m pleased to meet you.',
    'plenty': 'We have plenty of time.',
    'plus': 'Three plus two equals five.',
    'polite': 'He\'s very polite.',
    'poor': 'They are poor but happy.',
    'popular': 'This is a popular game.',
    'positive': 'Stay positive!',
    'possible': 'Is it possible to change the date?',
    'powerful': 'That\'s a powerful engine.',
    'practical': 'She\'s a practical person.',
    'present': 'All students were present.',
    'previous': 'The previous owner sold it.',
    'primary': 'This is my primary concern.',
    'private': 'This is private property.',
    'probably': 'It will probably rain.',
    'professional': 'He\'s a professional player.',
    'proper': 'Use the proper tools.',
    'proud': 'I\'m proud of you.',
    'public': 'This is a public park.',
    'pure': 'This is pure gold.',
    'purple': 'I like purple flowers.',
    'quick': 'That was quick!',
    'quiet': 'Please be quiet.',
    'quite': 'I\'m quite tired.',
    'rapid': 'There was rapid growth.',
    'rare': 'This is a rare book.',
    'rather': 'I\'m rather busy.',
    'rather than': 'I prefer walking rather than running.',
    'would rather': 'I would rather stay home.',
    'ready': 'Are you ready to go?',
    'real': 'Is this a real diamond?',
    'reasonable': 'That\'s a reasonable price.',
    'recent': 'This is a recent photo.',
    'red': 'I want the red one.',
    'regular': 'Come at your regular time.',
    'related': 'These issues are related.',
    'religious': 'They are religious people.',
    'responsible': 'He\'s a responsible person.',
    'rich': 'He\'s very rich.',
    'right': 'Your answer is right.',
    'rough': 'The sea is rough today.',
    'round': 'The earth is round.',
    'rude': 'Don\'t be rude!',
    'sad': 'Why do you look sad?',
    'safe': 'Is it safe to swim here?',
    'same': 'We\'re in the same class.',
    'satisfied': 'Are you satisfied with the result?',
    'scared': 'I\'m scared of spiders.',
    'secret': 'This is a secret message.',
    'sensible': 'That\'s a sensible decision.',
    'separate': 'Put them in separate boxes.',
    'serious': 'This is a serious problem.',
    'several': 'I called several times.',
    'sharp': 'This knife is sharp.',
    'short': 'He\'s quite short.',
    'should': 'You should study more.',
    'shy': 'She\'s a bit shy.',
    'sick': 'I feel sick.',
    'silent': 'Please remain silent.',
    'similar': 'These two are similar.',
    'similar to': 'This is similar to that one.',
    'simple': 'The answer is simple.',
    'since': 'I haven\'t seen him since Monday.',
    'single': 'Every single student passed.',
    'slow': 'The turtle is very slow.',
    'small': 'This shirt is too small.',
    'smooth': 'The surface is smooth.',
    'social': 'He has good social skills.',
    'soft': 'The pillow is soft.',
    'some': 'Would you like some tea?',
    'soon': 'I\'ll be there soon.',
    'sore': 'I have a sore throat.',
    'sorry': 'I\'m sorry I\'m late.',
    'south': 'They live in the south.',
    'special': 'This is a special day.',
    'specific': 'I need specific information.',
    'in spite of': 'In spite of the rain, we went out.',
    'square': 'The table is square.',
    'standard': 'This is the standard size.',
    'strange': 'That\'s a strange story.',
    'strong': 'He\'s very strong.',
    'stupid': 'That was a stupid thing to do.',
    'successful': 'The party was very successful.',
    'such': 'She\'s such a nice person.',
    'sudden': 'There was a sudden noise.',
    'sure': 'Are you sure about this?',
    'surprised': 'I was surprised to see him.',
    'sweet': 'This cake is too sweet.',
    'tall': 'He\'s very tall.',
    'terrible': 'What terrible news!',
    'than': 'She\'s taller than me.',
    'that': 'That book is mine.',
    'the': 'The book is on the table.',
    'their': 'Their house is big.',
    'theirs': 'The yellow car is theirs.',
    'them': 'Give it to them.',
    'then': 'First we\'ll eat, then we\'ll play.',
    'there': 'Put it there.',
    'these': 'These are my friends.',
    'thick': 'The walls are thick.',
    'thin': 'She\'s very thin.',
    'third': 'This is my third try.',
    'thirsty': 'I\'m thirsty.',
    'this': 'This is my house.',
    'those': 'Those books are old.',
    'though': 'I\'ll come, though I\'m tired.',
    'through': 'We walked through the park.',
    'tidy': 'Keep your room tidy.',
    'tight': 'These shoes are too tight.',
    'tiny': 'The baby is tiny.',
    'tired': 'I\'m very tired.',
    'together': 'Let\'s work together.',
    'top': 'Put it on the top shelf.',
    'total': 'What\'s the total amount?',
    'tough': 'This meat is tough.',
    'traditional': 'They wear traditional clothes.',
    'true': 'Is that story true?',
    'typical': 'That\'s typical of him.',
    'ugly': 'What an ugly building!',
    'unable': 'I\'m unable to come.',
    'uncertain': 'The future is uncertain.',
    'uncomfortable': 'This chair is uncomfortable.',
    'under': 'The cat is under the table.',
    'unhappy': 'He looks unhappy.',
    'unique': 'Each person is unique.',
    'unknown': 'The author is unknown.',
    'unless': 'I\'ll go unless it rains.',
    'unnecessary': 'That was unnecessary.',
    'unusual': 'That\'s unusual.',
    'up': 'Look up at the sky.',
    'upset': 'Don\'t be upset.',
    'upstairs': 'My room is upstairs.',
    'urgent': 'This is urgent!',
    'used': 'I bought a used car.',
    'useful': 'That\'s a useful tool.',
    'usual': 'Let\'s meet at the usual time.',
    'various': 'There are various options.',
    'vast': 'The desert is vast.',
    'violent': 'That was a violent storm.',
    'visible': 'The stars are visible tonight.',
    'warm': 'It\'s warm today.',
    'weak': 'I feel weak.',
    'wealthy': 'He comes from a wealthy family.',
    'weird': 'That\'s weird!',
    'welcome': 'You\'re always welcome here.',
    'well': 'I hope you\'re well.',
    'west': 'The sun sets in the west.',
    'wet': 'The floor is wet.',
    'whatever': 'Do whatever you like.',
    'which': 'Which color do you prefer?',
    'white': 'I want the white shoes.',
    'whole': 'I ate the whole pizza.',
    'whose': 'Whose bag is this?',
    'wide': 'The river is wide.',
    'wild': 'There are wild animals here.',
    'willing': 'I\'m willing to help.',
    'wise': 'That was a wise decision.',
    'with': 'Come with me.',
    'within': 'We must finish within an hour.',
    'without': 'I can\'t do it without help.',
    'wonderful': 'What a wonderful day!',
    'wooden': 'It\'s a wooden table.',
    'worse': 'The situation got worse.',
    'worst': 'That was the worst day ever.',
    'worth': 'How much is it worth?',
    'wrong': 'Your answer is wrong.',
    'yellow': 'I like the yellow one.',
    'yet': 'Are you finished yet?',
    'young': 'She\'s very young.',
    'yours': 'Is this book yours?',
}

def generate_default_sentence(word):
    """Generate a default sentence for words not in the mapping"""
    # For very simple cases
    if word.lower() in ['yes', 'no', 'ok']:
        return f'"{word.capitalize()}" is a common response.'

    # Default format
    return f'We use "{word}" in English.'

def main():
    print("Adding example sentences to words.csv...")

    # Read current words
    words = []
    with open('words.csv', 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        for row in reader:
            word_key = row['English Word']

            # Get sentence from mapping or generate default
            if word_key in EXAMPLE_SENTENCES:
                sentence = EXAMPLE_SENTENCES[word_key]
            else:
                sentence = generate_default_sentence(word_key)

            row['Example Sentence'] = sentence
            words.append(row)

    # Add new fieldname if needed
    if 'Example Sentence' not in fieldnames:
        fieldnames = list(fieldnames) + ['Example Sentence']

    # Write back with sentences
    with open('words.csv', 'w', encoding='utf-8', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(words)

    print(f"\n✓ Added example sentences to all {len(words)} words!")

    # Show samples
    print(f"\nSample entries:")
    for i, word in enumerate(words[:5], 1):
        print(f"\n{i}. {word['English Word']}")
        print(f"   Hebrew: {word['Hebrew Translation']}")
        print(f"   Level: {word['Difficulty Level']}")
        print(f"   Example: {word['Example Sentence']}")

if __name__ == '__main__':
    main()
